import React, { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, RadarChart, Radar, PolarGrid, PolarAngleAxis, Cell, Legend } from "recharts";
import { motion } from "motion/react";
import { ArrowLeft, ArrowRight, TrendingUp, CheckCircle2, Clock, Target, Zap, GitBranch, ShieldCheck, Activity, BarChart2, Network, FileSearch, Info, AlertCircle } from "lucide-react";

const TREND_DATA=[{week:"Wk 1",actual:45.2,expected:46.6},{week:"Wk 2",actual:46.1,expected:46.6},{week:"Wk 3",actual:44.8,expected:46.6},{week:"Wk 4",actual:43.9,expected:46.6},{week:"Wk 5",actual:43.1,expected:46.6},{week:"Wk 6",actual:42.8,expected:46.6}];
const REGIONAL_DATA=[{region:"North",actual:-17.4,color:"#ff5f57"},{region:"South",actual:3.1,color:"#28c840"},{region:"East",actual:1.2,color:"#00d2ff"},{region:"West",actual:-2.1,color:"#febc2e"}];
const HYPOTHESIS_DATA=[{name:"Logistics Disruption",probability:82,color:"#28c840",status:"SUPPORTED"},{name:"Competitor Pricing",probability:46,color:"#febc2e",status:"CORRELATED"},{name:"Sales Performance",probability:21,color:"#ff5f57",status:"INSUFFICIENT"}];
const EVIDENCE_SIGNALS=[{signal:"Delivery Delays",value:"+31%",severity:"HIGH",color:"#ff5f57",reliability:94},{signal:"North Region Delays",value:"+44%",severity:"HIGH",color:"#ff5f57",reliability:91},{signal:"Customer Complaints",value:"+27%",severity:"HIGH",color:"#febc2e",reliability:88},{signal:"Competitor Pricing",value:"-12%",severity:"LOW",color:"#00d2ff",reliability:62},{signal:"Inventory Levels",value:"-8%",severity:"MEDIUM",color:"#febc2e",reliability:75},{signal:"Enterprise Churn",value:"+23%",severity:"HIGH",color:"#ff5f57",reliability:89}];
const RADAR_DATA=[{metric:"Delivery",logistics:88,pricing:30,sales:20},{metric:"Complaints",logistics:72,pricing:42,sales:35},{metric:"Revenue",logistics:65,pricing:55,sales:40},{metric:"Churn",logistics:78,pricing:38,sales:28},{metric:"Regional",logistics:90,pricing:20,sales:15}];

function Tip({active,payload,label}){if(!active||!payload?.length)return null;return(<div className="p-3 rounded-xl border border-white/15 bg-[#05050f]/95 text-xs space-y-1 shadow-2xl"><div className="font-bold text-white mb-1">{label}</div>{payload.map((p,i)=>(<div key={i} className="flex justify-between gap-4" style={{color:p.color||"#fff"}}><span className="capitalize">{p.name}:</span><span className="font-bold font-mono">{p.value}{(p.name==="actual"||p.name==="expected"||p.name==="projected"||p.name==="baseline")?"M":"%"}</span></div>))}</div>);}

function FlowNode({label,sub,color="#00d2ff",delay=0,highlight=false}){return(<motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay,duration:0.45}} className={`px-5 py-3 rounded-xl border text-center min-w-[190px] max-w-sm ${highlight?"bg-[#ff5f57]/10 border-[#ff5f57]/45 shadow-lg":"bg-white/[0.04] border-white/15"}`}><div className="text-xs font-bold" style={{color}}>{label}</div>{sub&&<div className="text-[10px] text-white/50 mt-0.5">{sub}</div>}</motion.div>);}
function FlowArrow({delay=0}){return(<motion.div initial={{opacity:0,scaleY:0}} animate={{opacity:1,scaleY:1}} transition={{delay,duration:0.25}} className="flex justify-center my-1"><div className="w-px h-6 bg-white/20 relative"><div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-0 h-0 border-l-[4px] border-r-[4px] border-t-[6px] border-l-transparent border-r-transparent border-t-white/30"/></div></motion.div>);}
function ABar({value,color,delay=0}){const[w,setW]=useState(0);useEffect(()=>{const t=setTimeout(()=>setW(value),delay*1000+500);return()=>clearTimeout(t);},[value,delay]);return(<div className="w-full bg-white/10 h-2 rounded-full overflow-hidden"><div className="h-full rounded-full transition-all duration-1000 ease-out" style={{width:`${w}%`,backgroundColor:color}}/></div>);}
function Card({children,className=""}){return <div className={`bg-[#12131e] border border-white/10 rounded-2xl p-5 sm:p-6 shadow-md ${className}`}>{children}</div>;}
function ST({icon:Icon,color="#00d2ff",children}){return(<div className="flex items-center gap-2 mb-4"><Icon className="w-4 h-4 shrink-0" style={{color}}/><h3 className="text-sm font-bold text-white uppercase tracking-wider">{children}</h3></div>);}

function Stage01(){return(<div className="space-y-6">
<div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{label:"Revenue Actual",value:"$42.8M",delta:"Down 8.2%",color:"#ff5f57"},{label:"Expected",value:"$46.6M",delta:"Q3 Baseline",color:"#00d2ff"},{label:"Variance",value:"-$3.8M",delta:"Gap",color:"#febc2e"},{label:"Complaints",value:"1,240",delta:"Up 18.2%",color:"#ff5f57"}].map((kpi,i)=>(<motion.div key={kpi.label} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*0.08}} className="bg-[#12131e] border border-white/10 rounded-2xl p-4 shadow-sm"><div className="text-[10px] text-white/40 uppercase tracking-wider">{kpi.label}</div><div className="text-2xl font-black text-white mt-1">{kpi.value}</div><div className="text-xs font-bold mt-0.5" style={{color:kpi.color}}>{kpi.delta}</div></motion.div>))}</div>
<Card><ST icon={Activity} color="#ff5f57">Weekly Revenue — Expected vs Actual</ST><p className="text-xs text-white/50 mb-4">Revenue deviation began Week 3 and accelerated through Week 6. The widening gap confirms a supply/logistics disruption — order volumes were up 2.4%, ruling out demand collapse.</p><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={TREND_DATA} margin={{top:10,right:10,left:-10,bottom:0}}><defs><linearGradient id="ag1" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ff5f57" stopOpacity={0.35}/><stop offset="95%" stopColor="#ff5f57" stopOpacity={0}/></linearGradient><linearGradient id="ag2" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#00d2ff" stopOpacity={0.15}/><stop offset="95%" stopColor="#00d2ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" vertical={false}/><XAxis dataKey="week" stroke="rgba(255,255,255,0.35)" fontSize={11}/><YAxis stroke="rgba(255,255,255,0.35)" fontSize={11} domain={[40,48]} tickFormatter={v=>`$${v}M`}/><Tooltip content={<Tip/>}/><Area type="monotone" dataKey="expected" name="expected" stroke="#00d2ff" strokeWidth={2} strokeDasharray="4 4" fill="url(#ag2)" dot={{r:3,fill:"#00d2ff"}}/><Area type="monotone" dataKey="actual" name="actual" stroke="#ff5f57" strokeWidth={2.5} fill="url(#ag1)" dot={{r:4,fill:"#ff5f57"}}/></AreaChart></ResponsiveContainer></div></Card>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
<Card><ST icon={BarChart2} color="#00d2ff">Regional Revenue % Change</ST><p className="text-xs text-white/50 mb-4">North is the sole outlier — South and East are near forecast, ruling out a company-wide demand issue.</p><div className="h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={REGIONAL_DATA} margin={{top:5,right:5,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" vertical={false}/><XAxis dataKey="region" stroke="rgba(255,255,255,0.35)" fontSize={11}/><YAxis stroke="rgba(255,255,255,0.35)" fontSize={11} tickFormatter={v=>v+"%"}/><Tooltip content={<Tip/>}/><Bar dataKey="actual" name="Change%" radius={[6,6,0,0]}>{REGIONAL_DATA.map((d,i)=><Cell key={i} fill={d.color}/>)}</Bar></BarChart></ResponsiveContainer></div></Card>
<Card><ST icon={Info} color="#febc2e">Key Business Findings</ST><div className="space-y-2.5">{[{text:"Revenue dropped $3.8M below Q3 target",sev:"CRITICAL",c:"#ff5f57"},{text:"North region is sole outlier (-17.4%)",sev:"HIGH",c:"#ff5f57"},{text:"Order volume up 2.4% — demand intact",sev:"INFO",c:"#00d2ff"},{text:"Enterprise customers down 23.1%",sev:"HIGH",c:"#febc2e"},{text:"Delivery delays spiked 39% in North",sev:"HIGH",c:"#ff5f57"},{text:"Customer complaints up 18.2%",sev:"MEDIUM",c:"#febc2e"}].map((f,i)=>(<div key={i} className="flex items-start gap-2.5 p-2.5 rounded-xl bg-white/[0.03] border border-white/[0.06]"><span className="px-1.5 py-0.5 rounded text-[9px] font-bold shrink-0" style={{color:f.c,background:f.c+"22"}}>{f.sev}</span><span className="text-xs text-white/75">{f.text}</span></div>))}</div></Card>
</div>
<Card><ST icon={Clock} color="#A4F4FD">Anomaly Detection Timeline</ST><div className="relative pl-6 space-y-4"><div className="absolute left-2 top-0 bottom-0 w-px bg-white/10"/>{[{date:"Aug 4",text:"Revenue begins dipping below weekly baseline",c:"#febc2e"},{date:"Aug 11",text:"North delivery SLA breach detected (+12% delay)",c:"#febc2e"},{date:"Aug 14",text:"Enterprise complaint escalation flag triggered",c:"#ff5f57"},{date:"Aug 18",text:"Anomaly threshold breached — AI investigation initiated",c:"#ff5f57"},{date:"Aug 21",text:"Root cause isolated: North logistics partners (87% confidence)",c:"#28c840"}].map((t,i)=>(<div key={i} className="flex gap-3 items-start relative"><div className="absolute -left-[18px] w-3 h-3 rounded-full border-2 border-[#05050f] mt-0.5" style={{background:t.c}}/><div><div className="text-[10px] text-white/40 font-mono">{t.date}</div><div className="text-xs text-white/80 mt-0.5">{t.text}</div></div></div>))}</div></Card>
</div>);}

function Stage02(){return(<div className="space-y-6">
<Card><ST icon={GitBranch} color="#00d2ff">Root Cause Decomposition Flowchart</ST><p className="text-xs text-white/50 mb-6">Multi-level dimensional decomposition — each node tested at p &lt; 0.05 statistical significance before elevation in the chain.</p><div className="flex flex-col items-center">{[{label:"Revenue Anomaly",sub:"Down 8.2% | $3.8M gap",color:"#ff5f57",hl:true},{label:"North Region",sub:"Down 17.4% | PRIMARY ANOMALY",color:"#ff5f57",hl:true},{label:"Enterprise Customers",sub:"Down 23.1% | 87% confidence",color:"#febc2e",hl:false},{label:"Delayed Orders",sub:"Up 39% | Root signal",color:"#ff5f57",hl:true}].map((n,i)=>(<React.Fragment key={n.label}><FlowNode label={n.label} sub={n.sub} color={n.color} delay={i*0.14} highlight={n.hl}/>{i<3&&<FlowArrow delay={i*0.14+0.07}/>}</React.Fragment>))}</div></Card>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
<Card><ST icon={BarChart2} color="#ff5f57">Regional Isolation Analysis</ST><div className="space-y-3">{[{region:"North",change:-17.4,orders:"42K",anomaly:true},{region:"South",change:+3.1,orders:"61K",anomaly:false},{region:"East",change:+1.2,orders:"48K",anomaly:false},{region:"West",change:-2.1,orders:"33K",anomaly:false}].map(r=>(<div key={r.region} className={`flex items-center justify-between p-3 rounded-xl border ${r.anomaly?"bg-[#ff5f57]/08 border-[#ff5f57]/30":"bg-white/[0.03] border-white/10"}`}><div className="flex items-center gap-3">{r.anomaly&&<span className="w-2 h-2 rounded-full bg-[#ff5f57] animate-pulse"/>}<span className="text-sm font-semibold text-white">{r.region}</span></div><div className="flex items-center gap-4 text-xs"><span className="text-white/50">{r.orders} orders</span><span className={`font-bold ${r.change<0?"text-[#ff5f57]":"text-[#28c840]"}`}>{r.change>0?"+":""}{r.change}%</span></div></div>))}</div></Card>
<Card><ST icon={Network} color="#6366f1">Customer Segment Breakdown</ST><p className="text-xs text-white/50 mb-4">Enterprise accounts with SLA-sensitive contracts drove 68% of the revenue loss in North.</p><div className="space-y-4">{[{seg:"Enterprise",change:-23.1,contribution:"68%",color:"#ff5f57"},{seg:"Mid-Market",change:-9.4,contribution:"22%",color:"#febc2e"},{seg:"SMB / Consumer",change:-1.2,contribution:"10%",color:"#00d2ff"}].map(s=>(<div key={s.seg} className="space-y-1"><div className="flex justify-between text-xs"><span className="text-white font-medium">{s.seg}</span><div className="flex gap-3"><span className="text-white/40">{s.contribution} of loss</span><span className="font-bold" style={{color:s.color}}>{s.change}%</span></div></div><ABar value={Math.abs(s.change)*3} color={s.color} delay={0.2}/></div>))}</div><div className="mt-4 p-3 rounded-xl bg-[#ff5f57]/08 border border-[#ff5f57]/20 text-xs text-white/60 leading-relaxed"><span className="font-bold text-[#ff5f57]">Finding:</span> SLA breach triggers enterprise order cancellations, directly reducing recognized revenue.</div></Card>
</div>
</div>);}

function Stage03(){const[sel,setSel]=useState(null);return(<div className="space-y-6">
<Card><ST icon={FileSearch} color="#6366f1">Evidence Signal Matrix — Click any signal to inspect</ST><p className="text-xs text-white/50 mb-4">Six telemetry signals cross-referenced. Reliability reflects data quality and sample consistency. HIGH signals above 85% are treated as primary evidence.</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{EVIDENCE_SIGNALS.map((s,i)=>(<motion.div key={s.signal} initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} transition={{delay:i*0.07}} onClick={()=>setSel(sel===i?null:i)} className={`p-4 rounded-2xl border cursor-pointer transition-all ${sel===i?"border-white/30 bg-white/[0.07]":"border-white/10 bg-white/[0.03] hover:border-white/20"}`}><div className="flex justify-between mb-2"><span className="w-2.5 h-2.5 rounded-full mt-0.5" style={{background:s.color}}/><span className="px-2 py-0.5 rounded text-[9px] font-bold" style={{color:s.color,background:s.color+"22"}}>{s.severity}</span></div><div className="text-sm font-bold text-white mb-1">{s.signal}</div><div className="text-xl font-black" style={{color:s.color}}>{s.value}</div><div className="mt-2 space-y-1"><div className="flex justify-between text-[10px] text-white/40"><span>Reliability</span><span>{s.reliability}%</span></div><ABar value={s.reliability} color={s.color} delay={i*0.07}/></div></motion.div>))}</div></Card>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
<Card><ST icon={Activity} color="#A4F4FD">Hypothesis Signal Radar</ST><div className="h-56"><ResponsiveContainer width="100%" height="100%"><RadarChart data={RADAR_DATA}><PolarGrid stroke="rgba(255,255,255,0.1)"/><PolarAngleAxis dataKey="metric" tick={{fill:"rgba(255,255,255,0.5)",fontSize:11}}/><Radar name="Logistics" dataKey="logistics" stroke="#28c840" fill="#28c840" fillOpacity={0.2} strokeWidth={2}/><Radar name="Pricing" dataKey="pricing" stroke="#febc2e" fill="#febc2e" fillOpacity={0.1} strokeWidth={1.5}/><Radar name="Sales" dataKey="sales" stroke="#ff5f57" fill="#ff5f57" fillOpacity={0.08} strokeWidth={1}/><Legend formatter={v=><span style={{fontSize:11,color:"rgba(255,255,255,0.6)"}}>{v}</span>}/></RadarChart></ResponsiveContainer></div></Card>
<Card><ST icon={ShieldCheck} color="#28c840">Evidence Classification Tiers</ST><div className="space-y-3">{[{tier:"PRIMARY EVIDENCE",desc:"Delivery Delays, North Delays, Enterprise Churn",rel:"89-94%",color:"#28c840"},{tier:"SUPPORTING",desc:"Customer Complaints, Inventory Levels",rel:"75-88%",color:"#febc2e"},{tier:"CORRELATED",desc:"Competitor Pricing",rel:"62%",color:"#00d2ff"}].map(t=>(<div key={t.tier} className="p-4 rounded-xl border border-white/10 bg-white/[0.03]"><div className="flex justify-between items-center mb-1"><span className="text-[10px] font-bold uppercase tracking-wider" style={{color:t.color}}>{t.tier}</span><span className="text-[10px] text-white/40 font-mono">{t.rel}</span></div><p className="text-xs text-white/60">{t.desc}</p></div>))}<div className="p-3 rounded-xl bg-[#6366f1]/08 border border-[#6366f1]/20"><p className="text-xs text-white/55 leading-relaxed"><span className="font-bold text-[#A4F4FD]">Caution:</span> Correlation does not equal causation. All signals are FACT or CORRELATION. Causal proof requires controlled validation.</p></div></div></Card>
</div>
</div>);}

function Stage04(){const[slider,setSlider]=useState(82);return(<div className="space-y-6">
<Card><ST icon={Target} color="#28c840">Hypothesis Probability Analysis (Bayesian Scoring)</ST><p className="text-xs text-white/50 mb-5">Evidence supporting a hypothesis increases its posterior probability. Evidence contradicting it decreases it. Final probabilities reflect weighted evidence strength across all 6 signals.</p><div className="space-y-5">{HYPOTHESIS_DATA.map((h,i)=>(<div key={h.name}><div className="flex justify-between items-center mb-1.5"><span className="text-sm font-semibold text-white">{h.name}</span><div className="flex items-center gap-3"><span className="px-2 py-0.5 rounded text-[9px] font-bold" style={{color:h.color,background:h.color+"22"}}>{h.status}</span><span className="text-lg font-black" style={{color:h.color}}>{h.probability}%</span></div></div><ABar value={h.probability} color={h.color} delay={i*0.15}/></div>))}</div></Card>
<Card><ST icon={GitBranch} color="#28c840">Proposed Causal Chain (Hypothesis — Not Proven)</ST><div className="p-3 mb-4 rounded-xl bg-[#febc2e]/08 border border-[#febc2e]/25"><p className="text-xs text-[#febc2e]/80">Warning: Supported by correlation evidence only. Has NOT been validated via controlled experiment. Treat as most probable explanation, not confirmed fact.</p></div><div className="flex flex-col items-center space-y-1">{[{label:"North Logistics Partner Capacity Bottleneck",color:"#ff5f57"},{label:"Delivery SLA Breaches (Up 44% delay rate)",color:"#ff5f57"},{label:"Enterprise Customer Order Cancellations",color:"#febc2e"},{label:"Revenue Recognition Shortfall (Down 23.1%)",color:"#febc2e"},{label:"Overall Revenue Gap (-$3.8M, Down 8.2%)",color:"#ff5f57"}].map((n,i)=>(<React.Fragment key={i}><FlowNode label={n.label} color={n.color} delay={i*0.1}/>{i<4&&<FlowArrow delay={i*0.1+0.05}/>}</React.Fragment>))}</div></Card>
<Card><ST icon={Zap} color="#A4F4FD">Interactive Recovery Simulation</ST><div className="space-y-4"><div><div className="flex justify-between text-sm mb-2"><span className="text-white font-semibold">Logistics Hypothesis Confidence</span><span className="font-black text-[#28c840]">{slider}%</span></div><input type="range" min={0} max={100} value={slider} onChange={e=>setSlider(Number(e.target.value))} className="w-full h-2 rounded-full appearance-none cursor-pointer" style={{accentColor:"#28c840"}}/></div><div className="grid grid-cols-3 gap-4">{[{label:"Projected Recovery",value:`$${(3.8*slider/100).toFixed(1)}M`,color:"#28c840"},{label:"Residual Gap",value:`$${(3.8*(1-slider/100)).toFixed(1)}M`,color:"#ff5f57"},{label:"Confidence",value:`${slider}%`,color:"#00d2ff"}].map(s=>(<div key={s.label} className="p-4 rounded-xl bg-white/[0.03] border border-white/10 text-center"><div className="text-[10px] text-white/40 uppercase">{s.label}</div><div className="text-2xl font-black mt-1" style={{color:s.color}}>{s.value}</div></div>))}</div><p className="text-[10px] text-white/30 italic">Simulation assumes linear recovery. Actual outcomes depend on SLA renegotiation timeline and enterprise retention.</p></div></Card>
</div>);}

function Stage05(){const[step,setStep]=useState(1);const wf=[{label:"Identified",desc:"Anomaly detected and logged by AI",icon:AlertCircle,color:"#ff5f57"},{label:"Assigned",desc:"Ticket assigned to Operations",icon:CheckCircle2,color:"#febc2e"},{label:"Investigating",desc:"Auditing North logistics partners",icon:FileSearch,color:"#00d2ff"},{label:"Resolved",desc:"SLAs renegotiated, delays normalized",icon:CheckCircle2,color:"#28c840"}];const recovery=[{phase:"Week 1",projected:43.5,baseline:46.6},{phase:"Week 2",projected:44.8,baseline:46.6},{phase:"Week 3",projected:45.9,baseline:46.6},{phase:"Week 4",projected:46.5,baseline:46.6}];return(<div className="space-y-6">
<Card><ST icon={Zap} color="#ff5f57">Critical Action Ticket</ST><div className="p-5 rounded-2xl bg-[#ff5f57]/06 border border-[#ff5f57]/25"><div className="flex items-start justify-between gap-4 mb-4"><div><div className="text-[10px] text-white/40 font-mono uppercase mb-1">ACT-2024-0821-001</div><h4 className="text-lg font-bold text-white">Investigate North-Region Logistics Partners</h4><p className="text-xs text-white/60 mt-1 max-w-2xl leading-relaxed">Audit third-party logistics partners in North region. Review SLA compliance, identify breach patterns, enforce penalties, negotiate emergency capacity agreements to halt enterprise customer cancellations and restore revenue.</p></div><span className="px-3 py-1.5 rounded-xl bg-[#ff5f57]/20 text-[#ff5f57] text-xs font-black shrink-0">CRITICAL</span></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-white/10 text-xs">{[{label:"Owner",value:"Operations",color:"#00d2ff"},{label:"Priority",value:"CRITICAL",color:"#ff5f57"},{label:"Due",value:"Aug 28, 2024",color:"#febc2e"},{label:"Impact",value:"$3.8M",color:"#28c840"}].map(f=>(<div key={f.label}><div className="text-white/40 uppercase text-[9px]">{f.label}</div><div className="font-bold mt-0.5" style={{color:f.color}}>{f.value}</div></div>))}</div></div></Card>
<Card><ST icon={Activity} color="#00d2ff">Workflow Simulation — Click stages to advance</ST><div className="relative mt-2"><div className="absolute top-6 left-6 right-6 h-0.5 bg-white/10"><div className="h-full bg-[#00d2ff] transition-all duration-700" style={{width:`${(step/(wf.length-1))*100}%`}}/></div><div className="grid grid-cols-4 gap-2 relative">{wf.map((s,i)=>{const Icon=s.icon;const done=i<=step;return(<button key={s.label} onClick={()=>setStep(i)} className="flex flex-col items-center gap-2 text-center"><div className={`w-12 h-12 rounded-full border-2 flex items-center justify-center transition-all ${done?"border-[#00d2ff] bg-[#00d2ff]/15":"border-white/20 bg-white/5"}`}><Icon className="w-5 h-5" style={{color:done?s.color:"rgba(255,255,255,0.3)"}}/></div><div className={`text-[11px] font-semibold ${done?"text-white":"text-white/30"}`}>{s.label}</div><div className={`text-[10px] hidden sm:block leading-relaxed ${done?"text-white/55":"text-white/20"}`}>{s.desc}</div></button>);})}</div></div><div className="mt-4 p-3 rounded-xl bg-white/[0.03] border border-white/10 text-xs text-white/60">Current: <span className="font-bold text-[#00d2ff]">{wf[step].label}</span> — {wf[step].desc}</div></Card>
<Card><ST icon={TrendingUp} color="#28c840">Projected Revenue Recovery (Post-Action)</ST><p className="text-xs text-white/50 mb-4">If logistics partners restore SLA compliance within 1 week, revenue projects to recover to $46.5M by Week 4 (85% enterprise retention assumption).</p><div className="h-52"><ResponsiveContainer width="100%" height="100%"><AreaChart data={recovery} margin={{top:10,right:10,left:-10,bottom:0}}><defs><linearGradient id="rg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#28c840" stopOpacity={0.3}/><stop offset="95%" stopColor="#28c840" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" vertical={false}/><XAxis dataKey="phase" stroke="rgba(255,255,255,0.35)" fontSize={11}/><YAxis stroke="rgba(255,255,255,0.35)" fontSize={11} domain={[42,48]} tickFormatter={v=>`$${v}M`}/><Tooltip content={<Tip/>}/><Area type="monotone" dataKey="baseline" name="baseline" stroke="#00d2ff" strokeWidth={1.5} strokeDasharray="4 4" fill="none"/><Area type="monotone" dataKey="projected" name="projected" stroke="#28c840" strokeWidth={2.5} fill="url(#rg)"/></AreaChart></ResponsiveContainer></div></Card>
<Card><ST icon={CheckCircle2} color="#28c840">Sub-Action Checklist</ST><div className="space-y-2">{[{task:"Pull SLA compliance reports for all North partners (60 days)",owner:"Operations",done:true},{task:"Identify partners that exceeded delay thresholds (>3-day breach)",owner:"Logistics",done:true},{task:"Calculate SLA penalty amounts per contract terms",owner:"Legal",done:false},{task:"Initiate emergency capacity negotiations with top 3 North partners",owner:"Operations",done:false},{task:"Brief Enterprise account managers on resolution timeline",owner:"Sales",done:false},{task:"Offer proactive compensation to top-30 affected enterprise accounts",owner:"CX Team",done:false},{task:"Monitor delay rate — target: <5% within 7 days",owner:"Analytics",done:false}].map((item,i)=>(<div key={i} className={`flex items-start gap-3 p-3 rounded-xl border ${item.done?"bg-[#28c840]/05 border-[#28c840]/25":"bg-white/[0.03] border-white/[0.06]"}`}><div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 mt-0.5 ${item.done?"bg-[#28c840] border-[#28c840]":"border-white/30"}`}>{item.done&&<div className="w-1.5 h-1.5 rounded-full bg-white"/>}</div><span className={`text-xs flex-1 ${item.done?"text-white/40 line-through":"text-white/80"}`}>{item.task}</span><span className="text-[10px] text-white/30 shrink-0">{item.owner}</span></div>))}</div></Card>
</div>);}

const STAGES={"01":{num:"01",title:"Dashboard",subtitle:"What Happened?",color:"#ff5f57",Component:Stage01,summary:"Revenue fell $3.8M short of Q3 targets (down 8.2%). Anomaly began Week 3, concentrated in North region. Order volumes stable — demand intact, not a demand collapse."},"02":{num:"02",title:"Investigation",subtitle:"Where Did It Happen?",color:"#00d2ff",Component:Stage02,summary:"North region (down 17.4%) isolated as sole anomaly. Enterprise customers (down 23.1%) drove 68% of the loss, triggered by a 39% spike in delayed orders."},"03":{num:"03",title:"Evidence",subtitle:"What Evidence Do We Have?",color:"#6366f1",Component:Stage03,summary:"Six signals collected. Three primary (above 85% reliability): Delivery Delays +31%, North Delays +44%, Enterprise Churn +23%. Competitor pricing low-reliability / correlated only."},"04":{num:"04",title:"Recommendation",subtitle:"Why Is This Happening?",color:"#28c840",Component:Stage04,summary:"Logistics Disruption hypothesis 82% (SUPPORTED). Causal chain: logistics bottleneck → SLA breaches → enterprise cancellations → revenue gap. Use simulation to model recovery."},"05":{num:"05",title:"Action",subtitle:"What Should We Do Next?",color:"#febc2e",Component:Stage05,summary:"Critical action: Audit North logistics partners, enforce SLA penalties, negotiate emergency capacity. Projected $3.8M recovery over 4 weeks if action taken immediately."}};
const ORDER=["01","02","03","04","05"];

export default function StageDetail(){
  const{id}=useParams();const navigate=useNavigate();const stage=STAGES[id];
  useEffect(()=>{window.scrollTo(0,0);},[id]);
  if(!stage)return(<div className="flex items-center justify-center h-full text-white/50">Stage not found. <Link to="/dashboard" className="ml-2 text-[#00d2ff] underline">Back</Link></div>);
  const idx=ORDER.indexOf(id);const prevId=ORDER[idx-1];const nextId=ORDER[idx+1];const{Component}=stage;
  return(<div className="max-w-6xl mx-auto pb-16 space-y-6">
    <div className="flex items-center justify-between flex-wrap gap-3">
      <button onClick={()=>navigate("/dashboard")} className="flex items-center gap-2 text-xs text-white/60 hover:text-white transition-colors"><ArrowLeft className="w-4 h-4"/>Back to Intelligence Canvas</button>
      <div className="flex items-center gap-1.5">{ORDER.map(sid=>(<button key={sid} onClick={()=>navigate(`/stage/${sid}`)} className="w-7 h-7 rounded-lg text-[11px] font-bold transition-all" style={sid===id?{background:STAGES[sid].color+"33",color:STAGES[sid].color}:{background:"rgba(255,255,255,0.05)",color:"rgba(255,255,255,0.3)"}}>{sid}</button>))}</div>
    </div>
    <motion.div key={id} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:0.4,ease:[0.22,1,0.36,1]}} className="bg-[#12131e] border rounded-3xl p-6 sm:p-8 shadow-lg" style={{borderColor:stage.color+"40"}}>
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-4"><div className="px-4 py-2.5 rounded-2xl font-mono font-black text-2xl" style={{background:stage.color+"22",color:stage.color}}>{stage.num}</div><div><h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight">{stage.title}</h1><p className="text-sm text-white/50 mt-0.5">{stage.subtitle}</p></div></div>
        <div className="flex items-center gap-2">{prevId&&<button onClick={()=>navigate(`/stage/${prevId}`)} className="p-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-white/60 hover:text-white transition-all"><ArrowLeft className="w-4 h-4"/></button>}{nextId&&(<button onClick={()=>navigate(`/stage/${nextId}`)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-semibold transition-all hover:opacity-90" style={{background:STAGES[nextId].color+"20",borderColor:STAGES[nextId].color+"50",color:STAGES[nextId].color}}><span>Next: {STAGES[nextId].title}</span><ArrowRight className="w-4 h-4"/></button>)}</div>
      </div>
      <p className="text-sm text-white/60 mt-4 leading-relaxed max-w-3xl">{stage.summary}</p>
    </motion.div>
    <motion.div key={`c-${id}`} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:0.1,duration:0.4}}><Component/></motion.div>
    <div className="flex justify-between items-center pt-4 border-t border-white/10">
      {prevId?<button onClick={()=>navigate(`/stage/${prevId}`)} className="flex items-center gap-2 text-sm text-white/60 hover:text-white transition-colors"><ArrowLeft className="w-4 h-4"/>{STAGES[prevId].title}</button>:<div/>}
      <button onClick={()=>navigate("/dashboard")} className="text-xs text-white/30 hover:text-white transition-colors">Canvas Overview</button>
      {nextId?<button onClick={()=>navigate(`/stage/${nextId}`)} className="flex items-center gap-2 text-sm font-semibold transition-colors" style={{color:STAGES[nextId].color}}>{STAGES[nextId].title}<ArrowRight className="w-4 h-4"/></button>:<div/>}
    </div>
  </div>);
}
